app/routes/categorias.py
from flask import Blueprint, render_template, flash, redirect, request, url_for
from . import login
from api.models.categories import Category

bp = Blueprint('categorias', __name__, url_prefix='/categorias')

@bp.route('/')
def categorias():
    if login.current_user.is_authenticated:
        return render_template('pages/categorias/categorias.html')
    else:
        flash('Por favor, faça login para acessar esta página.', 'warning')
        return redirect(url_for('login.login'))

@bp.route('/adicionar')
def adicionar_categoria():
    if login.current_user.is_authenticated:
        return render_template('pages/categorias/adicionar_categoria.html')
    else:
        flash('Por favor, faça login para acessar esta página.', 'warning')
        return redirect(url_for('login.login'))

@bp.route('/editar/<int:id>')
def editar_categoria(id):
    if login.current_user.is_authenticated:
        category = Category.query.get_or_404(id)
        return render_template('pages/categorias/editar_categoria.html', category=category)
    else:
        flash('Por favor, faça login para acessar esta página.', 'warning')
        return redirect(url_for('login.login'))

app/templates/pages/categorias/adicionar_categoria.html
{% extends "base.html" %}

{% block content %}
    <div class="page-content">
        <h1 class="product-form-title">Adicionar Nova Categoria</h1>
        <form method="post" class="product-form-container" action="/api/categories">

            <div class="form-field">
                <label for="name">Nome da Categoria:</label>
                <input type="text" id="name" name="name" required class="login-input">
            </div>

            <div class="form-actions">
                <button type="submit" class="login-btn">Adicionar</button>
            </div>
        </form>
        <button onclick="window.location.href='{{ url_for('categorias.categorias') }}'" class="action-btn cancel">Cancelar</button>
    </div>
{% endblock %}

app/templates/pages/categorias/categorias.html
{% extends "base.html" %}

{% block content %}
    <div class="page-content">
        <div class="header-container">
            <h1>Categorias</h1>
            <button onclick="window.location.href='{{ url_for('categorias.adicionar_categoria') }}'" class="action-btn add">Adicionar Nova Categoria</button>
        </div>        

        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody id="categoriesTable">
            </tbody>
        </table>
        <script src="{{ url_for('static', filename='js/categorias/categorias.js') }}" defer></script>
    </div>
{% endblock %}

app/templates/pages/categorias/editar_categoria.html
{% extends "base.html" %}

{% block content %}
    <div class="page-content">
        <h1 class="product-form-title">Editar Categoria</h1>
        <form method="post" class="product-form-container" action="/api/categories/{{ category.id }}">

            <div class="form-field">
                <label for="name">Nome da Categoria:</label>
                <input type="text" id="name" name="name" value="{{ category.name }}" required class="login-input">
            </div>

            <div class="form-actions">
                <button type="submit" class="login-btn">Salvar Alterações</button>
            </div>
        </form>
        <button onclick="window.location.href='{{ url_for('categorias.categorias') }}'" class="action-btn cancel">Cancelar</button>
    </div>
{% endblock %}