app/routes/produtos.py
from flask import Blueprint, render_template, flash, redirect, url_for
from . import login
from api.models.products import Product

bp = Blueprint('produtos', __name__, url_prefix='/produtos')

@bp.route('/')
def produtos():
    if login.current_user.is_authenticated:
        return render_template('pages/produtos/produtos.html')
    else:
        flash('Por favor, faça login para acessar esta página.', 'warning')
        return redirect(url_for('login.login'))

@bp.route('/adicionar')
def adicionar_produto():
    if login.current_user.is_authenticated:
        return render_template('pages/produtos/adicionar_produto.html')
    else:
        flash('Por favor, faça login para acessar esta página.', 'warning')
        return redirect(url_for('login.login'))

@bp.route('/editar/<int:id>')
def editar_produto(id):
    if login.current_user.is_authenticated:
        product = Product.query.get_or_404(id)
        return render_template('pages/produtos/editar_produto.html', product=product)
    else:
        flash('Por favor, faça login para acessar esta página.', 'warning')
        return redirect(url_for('login.login'))

app/templates/pages/produtos/adicionar_produto.html
{% extends "base.html" %}

{% block content %}

    <div class="page-content">
        <h1 class="product-form-title">Adicionar Novo Produto</h1>
        <form method="post" class="product-form-container" action="/api/products" enctype="multipart/form-data">
            
            <div class="form-field">
                <label for="name">Nome do Produto:</label>
                <input type="text" id="name" name="name" required class="login-input">
            </div>

            <div class="form-field">
                <label for="photo">Foto do Produto:</label>
                <input type="file" id="photo" name="photo" accept="image/*" required class="login-input">
            </div>

            <div class="form-field">
                <label for="description">Descrição:</label>
                <textarea id="description" name="description" required class="login-input"></textarea>
            </div>

            <div class="form-field">
                <label for="price">Preço:</label>
                <input type="number" step="0.01" id="price" name="price" required class="login-input">
            </div>

            <div class="form-field">
                <label for="categorySelect">Categoria:</label>
                <select id="categorySelect" name="category_id" required class="login-input">
                    <option value="">Carregando categorias...</option>
                </select>
            </div>

            <div class="form-actions">
                <button type="submit" class="login-btn">Adicionar</button>
            </div>
        </form>

        <button onclick="window.location.href='{{ url_for('produtos.produtos') }}'" class="action-btn cancel">Cancelar</button>
    </div>

    <script src="{{ url_for('static', filename='js/produtos/adicionarProduto.js') }}" defer></script>

{% endblock %}

app/templates/pages/produtos/editar_produto.html
{% extends "base.html" %}

{% block content %}

    <div class="page-content">
        <h1 class="product-form-title">Editar Produto</h1>
        <form method="POST" action="/api/products/{{ product.id }}" enctype="multipart/form-data" class="product-form-container">
            
            <div class="form-field">
                <label for="name">Nome:</label>
                <input type="text" name="name" id="name" value="{{ product.name }}" required class="login-input">
            </div>

            <div class="form-field">
                <label for="description">Descrição:</label>
                <textarea name="description" id="description" class="login-input" required>{{ product.description }}</textarea>
            </div>

            <div class="form-field">
                <label for="price">Preço:</label>
                <input type="number" step="0.01" name="price" id="price" value="{{ product.price }}" required class="login-input">
            </div>

            <div class="form-field">
                <label for="categorySelect">Categoria:</label>
                <select id="categorySelect" name="category_id" required class="login-input" data-selected-category="{{ product.category_id }}">
                    <option value="">Selecione uma categoria</option>
                </select>
            </div>
            

            <div class="form-field">
                <label for="photo">Foto do Produto:</label>
                {% if product.photo_url %}
                    <img src="{{ url_for('static', filename='img/produtos') }}/{{ product.photo_url }}" alt="Foto atual do produto" style="max-width: 150px;">
                {% endif %}
                <input type="file" name="photo" id="photo" class="login-input">
            </div>

            <div class="form-actions">
                <button type="submit" class="login-btn">Salvar Alterações</button>
            </div>
        </form>

        <button onclick="window.location.href='{{ url_for('produtos.produtos') }}'" class="action-btn cancel">Cancelar</button>
    </div>

    <script src="{{ url_for('static', filename='js/produtos/editarProduto.js') }}" defer></script>

{% endblock %}

app/templates/pages/produtos/produtos.html
{% extends "base.html" %}

{% block content %}

    <div class="page-content">
        <div class="header-container">
            <h1>Produtos</h1>
            <button onclick="window.location.href='{{ url_for('produtos.adicionar_produto') }}'" class="action-btn add">Adicionar Novo Produto</button>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Preço</th>
                    <th>Categoria</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody id="productsTable">
            </tbody>
        </table>
    </div>

    <script src="{{ url_for('static', filename='js/produtos/produtos.js') }}" defer></script>

{% endblock %}