app/routes/usuarios.py
from flask import Blueprint, render_template, flash, redirect, url_for
from . import login
from api.models.users import User

bp = Blueprint('usuarios', __name__, url_prefix='/usuarios')

@bp.route('/')
def usuarios():
    if login.current_user.is_authenticated:
        return render_template('pages/usuarios/usuarios.html')
    else:
        flash('Por favor, faça login para acessar esta página.', 'warning')
        return redirect(url_for('login.login'))

@bp.route('/adicionar')
def adicionar_usuario():
    if login.current_user.is_authenticated:
        return render_template('pages/usuarios/adicionar_usuario.html')
    else:
        flash('Por favor, faça login para acessar esta página.', 'warning')
        return redirect(url_for('login.login'))

@bp.route('/editar/<int:id>')
def editar_usuario(id):
    if login.current_user.is_authenticated:
        user = User.query.get_or_404(id)
        return render_template('pages/usuarios/editar_usuario.html', user=user)
    else:
        flash('Por favor, faça login para acessar esta página.', 'warning')
        return redirect(url_for('login.login'))

app/templates/pages/usuarios/adicionar_usuario.html
{% extends "base.html" %}

{% block content %}
    <div class="page-content">
        <h1 class="product-form-title">Adicionar Novo Usuário</h1>
        <form method="post" class="product-form-container" action="/api/users">

            <div class="form-field">
                <label for="name">Nome:</label>
                <input type="text" id="name" name="name" required class="login-input">
            </div>

            <div class="form-field">
                <label for="username">Usuário:</label>
                <input type="text" id="username" name="username" required class="login-input">
            </div>

            <div class="form-field">
                <label for="password">Senha:</label>
                <input type="password" id="password" name="password" required class="login-input">
            </div>

            <div class="form-field">
                <label for="role">Cargo:</label>
                <select id="role" name="role" required class="login-input">
                    <option value="" disabled selected>Selecione um cargo</option>
                    <option value="Admin">Administrador</option>
                    <option value="Moder">Moderador</option>
                </select>
            </div>

            <div class="form-actions">
                <button type="submit" class="login-btn">Adicionar</button>
            </div>

        </form>
        <button onclick="window.location.href='{{ url_for('usuarios.usuarios') }}'" class="action-btn cancel">Cancelar</button>
    </div>
{% endblock %}

app/templates/pages/usuarios/editar_usuario.html
{% extends "base.html" %}

{% block content %}
    <div class="page-content">
        <h1 class="product-form-title">Editar Usuário</h1>
        <form method="post" class="product-form-container" action="/api/users/{{ user.id }}">

            <div class="form-field">
                <label for="name">Nome:</label>
                <input type="text" id="name" name="name" value="{{ user.name }}" required class="login-input">
            </div>

            <div class="form-field">
                <label for="username">Usuário:</label>
                <input type="text" id="username" name="username" value="{{ user.username }}" required class="login-input">
            </div>

            <div class="form-field">
                <label for="password">Senha:</label>
                <input type="password" id="password" name="password" value="" required class="login-input">
            </div>

            <div class="form-field">
                <label for="role">Cargo:</label>
                <select id="role" name="role" required class="login-input">
                    <option value="" disabled selected>Selecione um cargo</option>
                    <option value="Admin" {% if user.role == 'Admin' %}selected{% endif %}>Administrador</option>
                    <option value="Moder" {% if user.role == 'Moder' %}selected{% endif %}>Moderador</option>
                </select>
            </div>
            
            <div class="form-actions">
                <button type="submit" class="login-btn">Salvar Alterações</button>
            </div>
        </form>
        <button onclick="window.location.href='{{ url_for('usuarios.usuarios') }}'" class="action-btn cancel">Cancelar</button>
    </div>
{% endblock %}

app/templates/pages/usuarios/usuarios.html
{% extends "base.html" %}

{% block content %}
    <div class="page-content">
        <div class="header-container">
            <h1>Usuários</h1>
            <button onclick="window.location.href='{{ url_for('usuarios.adicionar_usuario') }}'" class="action-btn add">Adicionar Novo Usuário</button>
        </div>
    </div>
    
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Usuário</th>
                <th>Cargo</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody id="usersTable">
        </tbody>
    </table>
    <script src="{{ url_for('static', filename='js/usuarios/usuarios.js') }}" defer></script>
{% endblock %}